name: Mac OS Builds

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Mac OS Build
    permissions: write-all
    runs-on: macos-26
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s
      - name: Building the game
        run: |
          haxelib run lime build mac
      - name: Tar files
        run: tar -zcvf CodenameEngine.tar.gz -C export/release/macos/bin .
      - name: Uploading artifact (executable)
        uses: actions/upload-artifact@v4
        with:
          name: Codename Engine (Executable Only)
          path: export/release/macos/bin/CodenameEngine.app/Contents/MacOS/CodenameEngine
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: Codename Engine
          path: CodenameEngine.tar.gz