name: Windows Builds

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Windows Build
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s --no-vscheck
      - name: Building the game
        run: |
          haxelib run lime build windows
      - name: Uploading artifact (executable)
        uses: actions/upload-artifact@v4
        with:
          name: Codename Engine (Executable Only)
          path: export/release/windows/bin/CodenameEngine.exe
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: Codename Engine
          path: export/release/windows/bin